# Generated by Django 3.2.9 on 2022-05-16 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('anime', 'anime'), ('beauty', 'beauty'), ('business & finance', 'business & finance'), ('education', 'education'), ('entertainment', 'entertainment'), ('fashion', 'fashion'), ('food', 'food'), ('government & Politics', 'government & politics'), ('lifestyle', 'lifestyle'), ('movies', 'movies'), ('music', 'music'), ('others', 'others'), ('relationships', 'relationships'), ('religion', 'religion'), ('sports', 'sports'), ('technology', 'technology')], max_length=50)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='jpeg', keep_meta=True, null=True, quality=100, size=[320, 280], upload_to='blog_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
